require('dotenv').config();

module.exports = {
  env: {
    REACT_APP_AUTH0_DOMAIN: process.env.REACT_APP_AUTH0_DOMAIN,
    REACT_APP_AUTH0_CLIENT_ID: process.env.REACT_APP_AUTH0_CLIENT_ID,
    REACT_APP_HASURA_ENDPOINT: process.env.REACT_APP_HASURA_ENDPOINT,
    REACT_APP_HASURA_SOCKET_ENDPOINT: process.env.REACT_APP_HASURA_SOCKET_ENDPOINT,
  },
};
